"""add embedding column to transcripts

Revision ID: 1e5d7971fd36
Revises: 2c5ed3cd2d1c
Create Date: 2026-09-21 19:46:48.916558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5d7971fd36'
down_revision: Union[str, Sequence[str], None] = '2c5ed3cd2d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
